### ISSUE TITLE
Why I’ve been removed of the “Bitcoin” organization"

### ISSUE THREAD

**Issue by ariard** [bitcoin-core/meta#11]
Thanks if someone can come up with a public explanation on why I’ve been removed from the “Bitcoin” organization.

My latest open PR on the repository to improve the code has been opened in date of August 2 2024.

This is _weird_, it’s happening at the same time than a CoreDev edition might be happening.

Here the screenshot:

<img width="1083" alt="bitcoin-organization" src="https://github.com/user-attachments/assets/bad00911-3381-4679-a93c-e102e416472b">

**Comment by ariard** [comment]
@laanwj as a former maintainer if you have more information here.

**Comment by ariard** [comment]
@achow101 if you have further information too on this issue.

This could be also the bitcoin core github technical infrastructure, which has been compromised in a way or another. Under that regard, it would be good to modify with celerity any security information sharing policy that can be ongoing. If `bitcoind` github repository is compromised, there also other well-maintained full nodes in the ecosystem, e.g the `libre-relay` fork: https://github.com/petertodd/bitcoin/tree/libre-relay-v28.0

**Comment by achow101** [comment]
You were removed as part of a cleanup of the organization members where 10-15 people who were no longer regularly contributing ended up being removed. Several new contributors were added at the same time.

Your removal was because I believed you to be no longer regularly contributing or reviewing code.

Inclusion in the org is almost entirely to allow regular contributors, particularly reviewers, to have their review requested on PRs. As such, people who are not actively doing so should be removed from it. Membership in the org is largely inconsequential - it does not confer any special privileges or rights. You are still free to contribute as you wish and to participate as you have been.

**Comment by ariard** [comment]
I don’t disagree that membership in the github org is largely inconsequential, and personally I’ve little care to be part of the org. FWIW, sooner the project would have moved out of GH, better it will be in my opinion.

About your belief on regularity, I think it’s erroneous as I still have open PRs aiming to improve issues which have been discussed _years_ ago and from times to times I’m still reviewing PR or issues. This is very correct that I’m less active that in another period, though in the meantime it’s not like what was broken years ago have fundamentally improve, be it consensus, P2P or mempool.

For the future when you’re dropping a whole batch of folks from the organization, may I recommend you something ? It would have been good to take 2 minutes to write an email to the affected folks. Especially, when it’s happening at the same time than a private meeting. That way people affected don’t have to questions the admins intentions, or at minima to verify it’s not a more serious infrastructure issue. Style of communications matters in FOSS.

**Comment by ariard** [comment]
That can be closed, clarification is satisfying and we all have code to write and review.
